// This file is part of Soil.

// Copyright (C) Soil contributors.
// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-or-later WITH Classpath-exception-2.0

//! Autogenerated weights for `plant_remark`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-11-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-wiukf8gn-project-674-concurrent-0`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/soil-test-staging-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=plant_remark
// --no-storage-info
// --no-median-slopes
// --no-min-squares
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./substrate/frame/remark/src/weights.rs
// --header=./substrate/HEADER
// --template=./substrate/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use topsoil_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `plant_remark`.
pub trait WeightInfo {
	fn store(l: u32, ) -> Weight;
}

/// Weights for `plant_remark` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: topsoil_system::Config> WeightInfo for SubstrateWeight<T> {
	/// The range of component `l` is `[1, 1048576]`.
	fn store(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_242_000 picoseconds.
		Weight::from_parts(15_241_545, 0)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1_643, 0).saturating_mul(l.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// The range of component `l` is `[1, 1048576]`.
	fn store(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_242_000 picoseconds.
		Weight::from_parts(15_241_545, 0)
			// Standard Error: 0
			.saturating_add(Weight::from_parts(1_643, 0).saturating_mul(l.into()))
	}
}
