// This file is part of Soil.

// Copyright (C) Soil contributors.
// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

//! Substrate transaction API.
//!
//! The transaction methods allow submitting a transaction and subscribing to
//! its status updates generated by the chain.
//!
//! # Note
//!
//! Methods are prefixed by `transaction`.

#[cfg(test)]
mod tests;

mod metrics;

pub mod api;
pub mod error;
pub mod event;
pub mod transaction;
pub mod transaction_broadcast;

pub use api::{TransactionApiServer, TransactionBroadcastApiServer};
pub use event::{TransactionBlock, TransactionDropped, TransactionError, TransactionEvent};
pub use metrics::Metrics as TransactionMetrics;
pub use transaction::Transaction;
pub use transaction_broadcast::TransactionBroadcast;
