// This file is part of Soil.

// Copyright (C) Soil contributors.
// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-or-later WITH Classpath-exception-2.0

//! Autogenerated weights for plant_node_authorization

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use topsoil::weights_prelude::*;

pub trait WeightInfo {
	fn add_well_known_node() -> Weight;
	fn remove_well_known_node() -> Weight;
	fn swap_well_known_node() -> Weight;
	fn reset_well_known_nodes() -> Weight;
	fn claim_node() -> Weight;
	fn remove_claim() -> Weight;
	fn transfer_node() -> Weight;
	fn add_connections() -> Weight;
	fn remove_connections() -> Weight;
}

impl WeightInfo for () {
	fn add_well_known_node() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn remove_well_known_node() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn swap_well_known_node() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn reset_well_known_nodes() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn claim_node() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn remove_claim() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn transfer_node() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn add_connections() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn remove_connections() -> Weight { Weight::from_parts(50_000_000, 0) }
}
