// This file is part of Soil.

// Copyright (C) Soil contributors.
// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-or-later WITH Classpath-exception-2.0

//! Autogenerated weights for plant_ranked_collective
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-19, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// /Users/gav/Core/substrate/target/release/substrate
// benchmark
// pallet
// --pallet
// topsoil-dummy-dim
// --extrinsic=*
// --chain=dev
// --steps=50
// --repeat=20
// --output=../../../frame/dummy-dim/src/weights.rs
// --template=../../../.maintain/frame-weight-template.hbs
// --header=../../../HEADER
// --record-proof

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use topsoil_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for plant_dummy_dim.
pub trait WeightInfo {
	fn reserve_ids(c: u32) -> Weight;
	fn renew_id_reservation() -> Weight;
	fn cancel_id_reservation() -> Weight;
	fn recognize_personhood(c: u32) -> Weight;
	fn suspend_personhood(c: u32) -> Weight;
	fn resume_personhood() -> Weight;
	fn start_mutation_session() -> Weight;
	fn end_mutation_session() -> Weight;
}

/// Weights for plant_dummy_dim using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: topsoil_system::Config> WeightInfo for SubstrateWeight<T> {
	fn reserve_ids(_c: u32) -> Weight { Weight::zero() }
	fn renew_id_reservation() -> Weight { Weight::zero() }
	fn cancel_id_reservation() -> Weight { Weight::zero() }
	fn recognize_personhood(_c: u32) -> Weight { Weight::zero() }
	fn suspend_personhood(_c: u32) -> Weight { Weight::zero() }
	fn resume_personhood() -> Weight { Weight::zero() }
	fn start_mutation_session() -> Weight { Weight::zero() }
	fn end_mutation_session() -> Weight { Weight::zero() }
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn reserve_ids(_c: u32) -> Weight { Weight::zero() }
	fn renew_id_reservation() -> Weight { Weight::zero() }
	fn cancel_id_reservation() -> Weight { Weight::zero() }
	fn recognize_personhood(_c: u32) -> Weight { Weight::zero() }
	fn suspend_personhood(_c: u32) -> Weight { Weight::zero() }
	fn resume_personhood() -> Weight { Weight::zero() }
	fn start_mutation_session() -> Weight { Weight::zero() }
	fn end_mutation_session() -> Weight { Weight::zero() }
}
