// This file is part of Soil.

// Copyright (C) Soil contributors.
// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-or-later WITH Classpath-exception-2.0

//! Autogenerated weights for `plant_election_provider::benchmarking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-23, STEPS: `1`, REPEAT: 1, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/substrate
// benchmark
// pallet
// --chain=dev
// --steps=1
// --repeat=1
// --pallet=plant_election_provider
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=frame/election-provider-support/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use topsoil_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `plant_election_provider::benchmarking`.
pub trait WeightInfo {
	fn phragmen(v: u32, t: u32, d: u32, ) -> Weight;
	fn phragmms(v: u32, t: u32, d: u32, ) -> Weight;
}

/// Weights for `plant_election_provider::benchmarking` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: topsoil_system::Config> WeightInfo for SubstrateWeight<T> {
	fn phragmen(v: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_parts(0 as u64, 0)
			// Standard Error: 667_000
			.saturating_add(Weight::from_parts(32_973_000 as u64, 0).saturating_mul(v as u64))
			// Standard Error: 1_334_000
			.saturating_add(Weight::from_parts(1_334_000 as u64, 0).saturating_mul(t as u64))
			// Standard Error: 60_644_000
			.saturating_add(Weight::from_parts(2_636_364_000 as u64, 0).saturating_mul(d as u64))
	}
	fn phragmms(v: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_parts(0 as u64, 0)
			// Standard Error: 73_000
			.saturating_add(Weight::from_parts(21_073_000 as u64, 0).saturating_mul(v as u64))
			// Standard Error: 146_000
			.saturating_add(Weight::from_parts(65_000 as u64, 0).saturating_mul(t as u64))
			// Standard Error: 6_649_000
			.saturating_add(Weight::from_parts(1_711_424_000 as u64, 0).saturating_mul(d as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn phragmen(v: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_parts(0 as u64, 0)
			// Standard Error: 667_000
			.saturating_add(Weight::from_parts(32_973_000 as u64, 0).saturating_mul(v as u64))
			// Standard Error: 1_334_000
			.saturating_add(Weight::from_parts(1_334_000 as u64, 0).saturating_mul(t as u64))
			// Standard Error: 60_644_000
			.saturating_add(Weight::from_parts(2_636_364_000 as u64, 0).saturating_mul(d as u64))
	}
	fn phragmms(v: u32, t: u32, d: u32, ) -> Weight {
		Weight::from_parts(0 as u64, 0)
			// Standard Error: 73_000
			.saturating_add(Weight::from_parts(21_073_000 as u64, 0).saturating_mul(v as u64))
			// Standard Error: 146_000
			.saturating_add(Weight::from_parts(65_000 as u64, 0).saturating_mul(t as u64))
			// Standard Error: 6_649_000
			.saturating_add(Weight::from_parts(1_711_424_000 as u64, 0).saturating_mul(d as u64))
	}
}
